# Generated by Django 6.0.1 on 2026-06-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('project_description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_required', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('decision', models.CharField(max_length=50)),
                ('breakdown', models.JSONField()),
                ('strengths', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('risk_factors', models.JSONField(default=list)),
                ('suggested_improvements', models.JSONField(default=list)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_triggered', models.BooleanField(default=False)),
                ('vapi_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='ai_agents.job')),
            ],
        ),
    ]
