# Generated by Django 6.0.6 on 2026-06-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_jobmatchresult_scheduled_call_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingClarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting to be sent'), ('sent', 'Sent — awaiting description'), ('described', 'Described — awaiting proposal request'), ('resolved', 'Resolved')], default='waiting', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('proposal_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_clarification', to='ai_agents.job')),
            ],
        ),
    ]
